data:
  IMAGES_PATH: "/mnt/d/DIT/First Sem/Computer Vision/EchoLens/DataSet/Images"
  captions_file: "/mnt/d/DIT/First Sem/Computer Vision/EchoLens/DataSet/captions.txt"

training:
  VOCAB_SIZE: 10000
  SEQ_LENGTH: 25
  EMBED_DIM: 512
  FF_DIM: 512
  BATCH_SIZE: 64
  EPOCHS: 1

paths:
  vocab_file: "vocab.json"
  encoder_path: "../encoder.pth"
  decoder_path: "../decoder.pth"

image_preprocessing:
  IMAGE_SIZE: (299, 299)
